apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grade-submission-api-ingress
  namespace: grade-demo
spec:
  rules:
    - host: api.grade-submission.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grade-submission-api
                port:
                  number: 3000